version: "3.1"
services:
  proxy:
    depends_on:
      - backend
      - frontend
    container_name: proxy
    image: nginx:stable-alpine
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    command: [ "nginx", "-g", "daemon off;" ]
    networks:
      - my-network
  backend:
    container_name: backend
    build: ./backend
    restart: always
    command:
      - uvicorn app.main:app --reload --host 0.0.0.0 --port 5000
    networks:
      - my-network
  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge